services:
  mongodb:
    image: mongo:latest
    container_name: pledgepoint-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-pledgepoint}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-pledgepoint_password}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-pledgepoint_db}
    ports:
      - '27027:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - pledgepoint-network

  mongo-gui:
    container_name: "pledgepoint-mongo-viewer"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4324:4321"
    environment:
      - MONGO_URL=mongodb://doqett-database:27017/doqett-security
    networks:
      - pledgepoint-network

  redis:
    image: redis:alpine
    container_name: pledgepoint-redis
    restart: always
    ports:
      - '6389:6379'
    volumes:
      - redis-data:/data
    networks:
      - pledgepoint-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pledgepoint-api
    restart: always
    env_file:
      - .env
    ports:
      - '3030:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - pledgepoint-network
    depends_on:
      - mongodb
      - redis

networks:
  pledgepoint-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
